In [1]:
import numpy as np 

In [17]:
np.random.rand(10,20)

array([[0.87611875, 0.05350959, 0.43875567, 0.56546581, 0.23219953,
        0.43595169, 0.41001975, 0.177458  , 0.04654967, 0.19381611,
        0.75263589, 0.47176871, 0.60909308, 0.1497446 , 0.39668014,
        0.74323589, 0.1191577 , 0.8328657 , 0.36026195, 0.5930062 ],
       [0.88626301, 0.86761747, 0.10606988, 0.47527104, 0.77108146,
        0.05402822, 0.90600286, 0.30450063, 0.98393008, 0.30717343,
        0.54287873, 0.93714115, 0.32778199, 0.85383788, 0.67410974,
        0.17638451, 0.78565062, 0.95052159, 0.77626193, 0.70242516],
       [0.15773011, 0.66175032, 0.31255817, 0.62015676, 0.92598249,
        0.39483591, 0.74903655, 0.93536877, 0.84476621, 0.33735302,
        0.41550732, 0.15816772, 0.6490524 , 0.60250038, 0.24450545,
        0.86610716, 0.48183352, 0.54716291, 0.58345063, 0.02512489],
       [0.7832474 , 0.79393065, 0.21122715, 0.07116629, 0.22217913,
        0.8158678 , 0.16506441, 0.90547201, 0.01073725, 0.09942796,
        0.810739  , 0.4926866 , 0.39992885, 0

In [10]:
np.random.randint(434)

242

In [16]:
np.random.randint(10,20,5)

array([11, 18, 17, 11, 19])

In [36]:
m= np.random.randint(10,40,(10,10))
m# matrix representaton 

array([[29, 24, 26, 31, 30, 11, 28, 14, 11, 21],
       [38, 36, 22, 10, 25, 25, 13, 39, 12, 22],
       [39, 18, 19, 37, 21, 24, 12, 32, 10, 23],
       [37, 10, 29, 38, 22, 21, 19, 26, 25, 14],
       [27, 15, 23, 17, 16, 21, 21, 34, 23, 34],
       [22, 17, 17, 32, 19, 39, 22, 13, 30, 27],
       [34, 37, 18, 29, 28, 22, 25, 28, 37, 16],
       [39, 10, 31, 25, 31, 11, 29, 25, 23, 13],
       [30, 11, 32, 33, 23, 25, 17, 23, 17, 35],
       [14, 15, 21, 23, 16, 16, 38, 30, 28, 11]])

In [23]:
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [27]:
nd = np.array(my_list)
nd

array([1, 2, 3, 4, 5])

In [28]:
nd

array([1, 2, 3, 4, 5])

In [35]:
nd.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

# slicing in matrix 

In [37]:
m

array([[29, 24, 26, 31, 30, 11, 28, 14, 11, 21],
       [38, 36, 22, 10, 25, 25, 13, 39, 12, 22],
       [39, 18, 19, 37, 21, 24, 12, 32, 10, 23],
       [37, 10, 29, 38, 22, 21, 19, 26, 25, 14],
       [27, 15, 23, 17, 16, 21, 21, 34, 23, 34],
       [22, 17, 17, 32, 19, 39, 22, 13, 30, 27],
       [34, 37, 18, 29, 28, 22, 25, 28, 37, 16],
       [39, 10, 31, 25, 31, 11, 29, 25, 23, 13],
       [30, 11, 32, 33, 23, 25, 17, 23, 17, 35],
       [14, 15, 21, 23, 16, 16, 38, 30, 28, 11]])

In [39]:
b=np.random.randint(10,20,(5,4))
b

array([[17, 10, 14, 13],
       [14, 14, 18, 15],
       [19, 14, 10, 17],
       [15, 19, 18, 10],
       [13, 11, 11, 14]])

In [40]:
b[:]

array([[17, 10, 14, 13],
       [14, 14, 18, 15],
       [19, 14, 10, 17],
       [15, 19, 18, 10],
       [13, 11, 11, 14]])

In [41]:
b[3:]

array([[15, 19, 18, 10],
       [13, 11, 11, 14]])

In [42]:
b[-1:]

array([[13, 11, 11, 14]])

In [43]:
b[:-1]

array([[17, 10, 14, 13],
       [14, 14, 18, 15],
       [19, 14, 10, 17],
       [15, 19, 18, 10]])