# array creation functions 

In [1]:
import numpy as np 

In [3]:
# crate an array from list 
a=np.array([1,2,3])
print('Array:',a)

Array: [1 2 3]


In [5]:
# crate an array with even values 
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros((2,3),dtype=int) # create an array with zeors 

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones((3,2),dtype=int) # 3x2 matrix print ones 

array([[1, 1],
       [1, 1],
       [1, 1]])

In [18]:
f=np.eye(5) # used to print itentified matrix 
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# array manuplation functions

In [21]:
# reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print(reshaped)

[[1 2 3]]


In [24]:
# flaten a array 
f1=np.array([[1,2],[3,4]])
flaten=np.ravel(f1)
print(flaten)

[1 2 3 4]


In [33]:
# tanspose an array 
e1=np.array([[1, 2], [6, 4]])
transpose=np.transpose(e1)
print(transpose)

[[1 6]
 [2 4]]


In [34]:
range(5)

range(0, 5)

In [35]:
r=range(6)
r

range(0, 6)

In [36]:
for i in r:
    print(i)
    

0
1
2
3
4
5


In [37]:
list(range(5))

[0, 1, 2, 3, 4]

In [38]:
range(1,10)

range(1, 10)

In [39]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
list(range(0,10,2)) # step count 

[0, 2, 4, 6, 8]

In [42]:
np.random.rand(5)

array([0.97155779, 0.57121592, 0.97954619, 0.96769707, 0.37290988])

In [54]:
np.random.rand(10,2) # prodice random in float in form of 10x2 matrix

array([[0.33536717, 0.4136959 ],
       [0.82464176, 0.2068119 ],
       [0.53451031, 0.61842129],
       [0.52172714, 0.9910489 ],
       [0.28011275, 0.92593371],
       [0.81464804, 0.08872122],
       [0.42370563, 0.04251441],
       [0.48847436, 0.35683997],
       [0.26992616, 0.56103561],
       [0.4283649 , 0.70070415]])

In [50]:
np.random.randint(10,20)

11

In [59]:
np.random.randint(0,10,6) # produce six random numbers in between 0and 10

array([2, 0, 5, 1, 8, 6])

In [56]:
np.random.randint(5,9)

6

In [58]:
np.random.randint(10,40,(10,10)) # generte the random numbers in form of matrix 

array([[32, 10, 38, 15, 27, 36, 28, 22, 33, 39],
       [39, 11, 32, 10, 17, 21, 26, 26, 14, 25],
       [21, 33, 17, 35, 30, 36, 38, 14, 38, 30],
       [19, 36, 13, 32, 15, 31, 39, 17, 33, 34],
       [21, 39, 19, 25, 22, 16, 19, 39, 29, 38],
       [32, 15, 19, 39, 30, 38, 17, 31, 14, 34],
       [29, 16, 19, 26, 22, 31, 32, 10, 19, 33],
       [34, 29, 13, 19, 28, 17, 33, 34, 37, 35],
       [15, 14, 15, 18, 16, 13, 26, 34, 21, 31],
       [30, 33, 20, 12, 35, 16, 29, 10, 34, 11]])

In [61]:
np.random.randint(1,100,(12,12))

array([[12, 57, 71, 66, 32, 20, 72, 37, 88, 10, 50, 91],
       [ 1, 19, 45, 61,  3, 29, 37, 23, 68, 79, 14, 91],
       [39, 81, 24, 38, 73, 23, 58, 22, 18, 58, 29, 92],
       [ 9, 95, 63, 22, 26, 72, 20, 80,  3, 66, 37, 62],
       [94, 81, 83, 32, 71,  5, 76, 69, 73, 76,  6, 21],
       [ 5, 59, 48, 16, 97,  5, 66, 91, 46, 55, 70, 44],
       [28, 28, 40, 13, 21, 41, 57,  3, 80, 77, 86, 91],
       [81, 34, 12, 58, 30, 75, 98, 93,  8, 32, 68, 24],
       [15, 97, 74, 23, 20, 89, 64, 76, 71, 52, 52, 14],
       [ 4, 34, 13, 17, 41, 73, 87, 88, 45, 80, 32, 91],
       [75, 99, 78, 18, 41, 98, 72, 47,  9,  7, 62,  4],
       [57, 90, 48, 30, 56, 46, 50,  4, 63, 27, 88, 67]])

In [65]:
np.arange(1,21).reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [66]:
b=np.random.randint(10,20,(5,4))
b

array([[11, 17, 18, 13],
       [18, 16, 19, 16],
       [15, 11, 14, 16],
       [13, 18, 12, 11],
       [17, 13, 15, 17]])

In [67]:
type(b)

numpy.ndarray

In [68]:
b

array([[11, 17, 18, 13],
       [18, 16, 19, 16],
       [15, 11, 14, 16],
       [13, 18, 12, 11],
       [17, 13, 15, 17]])

In [69]:
b[:]

array([[11, 17, 18, 13],
       [18, 16, 19, 16],
       [15, 11, 14, 16],
       [13, 18, 12, 11],
       [17, 13, 15, 17]])

In [70]:
b[2:]

array([[15, 11, 14, 16],
       [13, 18, 12, 11],
       [17, 13, 15, 17]])

In [71]:
b[1:3]

array([[18, 16, 19, 16],
       [15, 11, 14, 16]])

In [73]:
b[-4:-1]

array([[18, 16, 19, 16],
       [15, 11, 14, 16],
       [13, 18, 12, 11]])

In [75]:
b[1,2] # it is called secnod row third element beause the index starts fom the zero 

19

In [76]:
b[1,3]

16

In [78]:
b[1,-1]

16

In [79]:
b

array([[11, 17, 18, 13],
       [18, 16, 19, 16],
       [15, 11, 14, 16],
       [13, 18, 12, 11],
       [17, 13, 15, 17]])

In [80]:
b[0:-2]

array([[11, 17, 18, 13],
       [18, 16, 19, 16],
       [15, 11, 14, 16]])

In [81]:
b

array([[11, 17, 18, 13],
       [18, 16, 19, 16],
       [15, 11, 14, 16],
       [13, 18, 12, 11],
       [17, 13, 15, 17]])

In [82]:
b[-5:-3]

array([[11, 17, 18, 13],
       [18, 16, 19, 16]])

In [85]:
b[-5:2]

array([[11, 17, 18, 13],
       [18, 16, 19, 16]])

# operations 

In [86]:
a=np.random.randint(10,20,10)
a

array([16, 19, 17, 16, 10, 11, 11, 10, 14, 17])

In [89]:
a

array([16, 19, 17, 16, 10, 11, 11, 10, 14, 17])

In [90]:
arr2=np.random.randint(1,100,(10,10))
arr2

array([[31, 36,  5, 53, 15, 90, 37, 61, 58, 78],
       [ 8, 30,  2, 26, 19, 62, 93, 56, 70,  7],
       [92, 22, 61, 30, 20, 77, 24, 63, 89, 44],
       [40, 73,  1, 65, 29, 46, 49, 70, 49, 48],
       [21, 29, 90, 16, 56, 29, 25, 73, 67, 76],
       [66, 45, 62, 23, 41,  9, 53,  5, 69, 98],
       [ 6, 15, 12, 71, 98, 71, 21, 32, 25,  6],
       [13,  1, 10, 73, 97, 10, 24, 78, 11, 34],
       [44,  7, 74, 55, 84, 60,  5, 49, 65, 25],
       [24, 54, 76, 31, 26, 58, 29, 39,  8, 86]])

In [108]:
arr2[::-1] # reverses the matrix 

array([[24, 54, 76, 31, 26, 58, 29, 39,  8, 86],
       [44,  7, 74, 55, 84, 60,  5, 49, 65, 25],
       [13,  1, 10, 73, 97, 10, 24, 78, 11, 34],
       [ 6, 15, 12, 71, 98, 71, 21, 32, 25,  6],
       [66, 45, 62, 23, 41,  9, 53,  5, 69, 98],
       [21, 29, 90, 16, 56, 29, 25, 73, 67, 76],
       [40, 73,  1, 65, 29, 46, 49, 70, 49, 48],
       [92, 22, 61, 30, 20, 77, 24, 63, 89, 44],
       [ 8, 30,  2, 26, 19, 62, 93, 56, 70,  7],
       [31, 36,  5, 53, 15, 90, 37, 61, 58, 78]])

In [107]:
arr2[::3] # it returns the rows by taking 3 as step count 

array([[31, 36,  5, 53, 15, 90, 37, 61, 58, 78],
       [40, 73,  1, 65, 29, 46, 49, 70, 49, 48],
       [ 6, 15, 12, 71, 98, 71, 21, 32, 25,  6],
       [24, 54, 76, 31, 26, 58, 29, 39,  8, 86]])

In [105]:
arr2.max()

98

In [109]:
arr2.min()

1

In [110]:
a

array([16, 19, 17, 16, 10, 11, 11, 10, 14, 17])

In [111]:
a.reshape(5,2)

array([[16, 19],
       [17, 16],
       [10, 11],
       [11, 10],
       [14, 17]])

In [113]:
a.reshape(5,2,order='A')

array([[16, 19],
       [17, 16],
       [10, 11],
       [11, 10],
       [14, 17]])

In [115]:
arr2[3] # calling the rows 

array([40, 73,  1, 65, 29, 46, 49, 70, 49, 48])

In [116]:
arr2[:,4]

array([15, 19, 20, 29, 56, 41, 98, 97, 84, 26])

In [118]:
arr2

array([[31, 36,  5, 53, 15, 90, 37, 61, 58, 78],
       [ 8, 30,  2, 26, 19, 62, 93, 56, 70,  7],
       [92, 22, 61, 30, 20, 77, 24, 63, 89, 44],
       [40, 73,  1, 65, 29, 46, 49, 70, 49, 48],
       [21, 29, 90, 16, 56, 29, 25, 73, 67, 76],
       [66, 45, 62, 23, 41,  9, 53,  5, 69, 98],
       [ 6, 15, 12, 71, 98, 71, 21, 32, 25,  6],
       [13,  1, 10, 73, 97, 10, 24, 78, 11, 34],
       [44,  7, 74, 55, 84, 60,  5, 49, 65, 25],
       [24, 54, 76, 31, 26, 58, 29, 39,  8, 86]])

In [119]:
arr2[4,:]

array([21, 29, 90, 16, 56, 29, 25, 73, 67, 76])

In [120]:
arr2[:,8]

array([58, 70, 89, 49, 67, 69, 25, 11, 65,  8])

In [121]:
arr2[:4]

array([[31, 36,  5, 53, 15, 90, 37, 61, 58, 78],
       [ 8, 30,  2, 26, 19, 62, 93, 56, 70,  7],
       [92, 22, 61, 30, 20, 77, 24, 63, 89, 44],
       [40, 73,  1, 65, 29, 46, 49, 70, 49, 48]])

In [123]:
arr2[:,8] # fecting specific coloumn 

array([58, 70, 89, 49, 67, 69, 25, 11, 65,  8])

In [125]:
arr2[0:10:3]

array([[31, 36,  5, 53, 15, 90, 37, 61, 58, 78],
       [40, 73,  1, 65, 29, 46, 49, 70, 49, 48],
       [ 6, 15, 12, 71, 98, 71, 21, 32, 25,  6],
       [24, 54, 76, 31, 26, 58, 29, 39,  8, 86]])

In [127]:
arr2[2:6,2:4] # fecting specific row and cloumn at time 

array([[61, 30],
       [ 1, 65],
       [90, 16],
       [62, 23]])

# masking

In [128]:
arr2

array([[31, 36,  5, 53, 15, 90, 37, 61, 58, 78],
       [ 8, 30,  2, 26, 19, 62, 93, 56, 70,  7],
       [92, 22, 61, 30, 20, 77, 24, 63, 89, 44],
       [40, 73,  1, 65, 29, 46, 49, 70, 49, 48],
       [21, 29, 90, 16, 56, 29, 25, 73, 67, 76],
       [66, 45, 62, 23, 41,  9, 53,  5, 69, 98],
       [ 6, 15, 12, 71, 98, 71, 21, 32, 25,  6],
       [13,  1, 10, 73, 97, 10, 24, 78, 11, 34],
       [44,  7, 74, 55, 84, 60,  5, 49, 65, 25],
       [24, 54, 76, 31, 26, 58, 29, 39,  8, 86]])

In [130]:
arr2[arr2>50]

array([53, 90, 61, 58, 78, 62, 93, 56, 70, 92, 61, 77, 63, 89, 73, 65, 70,
       90, 56, 73, 67, 76, 66, 62, 53, 69, 98, 71, 98, 71, 73, 97, 78, 74,
       55, 84, 60, 65, 54, 76, 58, 86])

In [131]:
arr2<50

array([[ True,  True,  True, False,  True, False,  True, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
         True],
       [False,  True, False,  True,  True, False,  True, False, False,
         True],
       [ True, False,  True, False,  True,  True,  True, False,  True,
         True],
       [ True,  True, False,  True, False,  True,  True, False, False,
        False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False],
       [ True,  True,  True, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True, False, False,  True,  True, False,  True,
         True],
       [ True,  True, False, False, False, False,  True,  True, False,
         True],
       [ True, False, False,  True,  True, False,  True,  True,  True,
        False]])

In [137]:
arr2==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

# python programing to generate otp 

In [138]:
from numpy import*
def generate_otp(length=4):
    """Generate a numeric otp of a specified length."""
    digits='012345'
   
 